#!/usr/bin/python
import subprocess as sub
from uppmax import proj
import re
import sys

def main():
    projects_gen = proj.gen_projects()
    for p in projects_gen:
        print p.name

if __name__ == '__main__':
    main()
